language: ruby
cache: bundler

rvm:
  - ruby
  - 2.1.5

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - dstein-phins@hotmail.com
    on_failure: change
    on_success: never